name: Jekyll Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Build site
      run: bundle exec jekyll build --trace

    - name: Upload site (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site
